export default [
  {
    _id: "b1",
    volumeId: "zyTCAlFPjgYC",
    authorId: "a1",
    title: "Harry Potter and the Sorcerer's Stone",
    authors: ["J.K. Rowling"],
    coverImageUrl: "https://books.google.com/books/content?id=zyTCAlFPjgYC&printsec=frontcover&img=1&zoom=1",
    description: "Harry Potter discovers he is a wizard and attends Hogwarts School of Witchcraft and Wizardry.",
    pageCount: 309,
    genres: ["Fantasy", "Adventure"],
    ratingsId: "r1",
    publishedDate: "1997-06-26",
    updatedAt: new Date("2025-11-23T10:00:00Z"),
    notes: "First book in the Harry Potter series."
  },
  {
    _id: "b2",
    volumeId: "uWbTAAAAYAAJ",
    authorId: "a2",
    title: "The Hobbit",
    authors: ["J.R.R. Tolkien"],
    coverImageUrl: "https://books.google.com/books/content?id=uWbTAAAAYAAJ&printsec=frontcover&img=1&zoom=1",
    description: "Bilbo Baggins embarks on a quest to reclaim the lost Dwarf Kingdom of Erebor.",
    pageCount: 310,
    genres: ["Fantasy", "Classic"],
    ratingsId: "r2",
    publishedDate: "1937-09-21",
    updatedAt: new Date("2025-11-22T09:30:00Z"),
    notes: "Prequel to the Lord of the Rings trilogy."
  },
  {
    _id: "b3",
    volumeId: "m8dPPgAACAAJ",
    authorId: "a3",
    title: "To Kill a Mockingbird",
    authors: ["Harper Lee"],
    coverImageUrl: "https://books.google.com/books/content?id=m8dPPgAACAAJ&printsec=frontcover&img=1&zoom=1",
    description: "A novel about the serious issues of rape and racial inequality.",
    pageCount: 281,
    genres: ["Fiction", "Classic"],
    ratingsId: "r3",
    publishedDate: "1960-07-11",
    updatedAt: new Date("2025-11-20T15:00:00Z"),
    notes: "Pulitzer Prize-winning novel."
  },
  {
    _id: "b4",
    volumeId: "xYzTAAAAYAAJ",
    authorId: "a4",
    title: "1984",
    authors: ["George Orwell"],
    coverImageUrl: "https://books.google.com/books/content?id=xYzTAAAAYAAJ&printsec=frontcover&img=1&zoom=1",
    description: "A dystopian novel set in a totalitarian society ruled by Big Brother.",
    pageCount: 328,
    genres: ["Dystopian", "Science Fiction"],
    ratingsId: "r4",
    publishedDate: "1949-06-08",
    updatedAt: new Date("2025-11-21T12:00:00Z"),
    notes: "Classic dystopian literature."
  }
];